name: api call test

on:
  repository_dispatch:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tf/prod/Network
    steps:
      - uses: actions/checkout@v3
      - name: plan for network
        run: echo hi
