name: terraform apply(prod)
# main branch only !!
on:
  workflow_dispatch:
    inputs:
      infraType:
        description: "infrastructure type"
        required: true
        default: "Choose One"
        type: choice
        options:
        - Choose One
        - Backend
        - Frontend
        - Network
permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{secrets.AWS_ROLE_ARN}}
          aws-region: ap-northeast-1
      - name: Configure Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6
      - name: version check
        run: |
          aws --version
          terraform --version
      - name: branch check
        if: github.ref!='refs/heads/main'
        run: |
          echo "terraform apply runs on main branch only !"
          exit 1
      - name: input check
        if: inputs.infraType=='Choose One'
        run: |
          echo "choose infra type!"
          exit 1
      - name: terraform init
        working-directory: ./tf/prod${{ inputs.infraType }}
        run: terraform init
      - name: terraform apply
        working-directory: ./tf/prod${{ inputs.infraType }}
        run: terraform apply -auto-approve
