name: terraform apply
# main branch only !!
on:
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tf/prod
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{secrets.AWS_ROLE_ARN}}
          aws-region: ap-northeast-1
      - name: Configure Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6
      - name: version check
        run: |
          aws --version
          terraform --version
      - name: branch check
        if: github.ref!='refs/heads/main'
        run: |
          echo "terraform apply runs on main branch only !"
          exit 1
      - name: terraform init
        run: terraform init
      - name: terraform destroy
        run: terraform destroy -auto-approve
